services:

  mongodb:
    image: mongo:8.0
    ports:
      - "6379:6379"
    environment:
      MONGO_INITDB_DATABASE: throughtstreamdb
    networks:
      throughtstream_network:
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_volume:/mongo/db

  redis:
    image: redis:7.2
    ports:
      - "27017:27017"
    networks:
      throughtstream_network:
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8082:8080"
    networks:
      throughtstream_network:

networks:
  throughtstream_network:
    driver: bridge

volumes:
  mongodb_volume:
  rediscache_volume: