spring:
  application:
    name: ThoughtStream

  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379

  mongodb:
    uri: mongodb://localhost:27017/thoughtstreamdb


# CUSTOM ENVIRONMENT VARIABLES

jwt:
  secretKey: djklfhaiudhfliuahsjknsjfdngjksdflkghlsakndgpiuahdsbnvaiuksdhgvioubaijdscvh

pagination:
  pageSize: 10