spring:
  application:
    name: ThoughtStream

  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: redis
      port: 6379

  mongodb:
    uri: mongodb://mongodb:27017/thoughtstreamdb


# CUSTOM ENVIRONMENT VARIABLES

jwt:
  secretkey: djklfhaiudhfliuahsjknsjfdngjksdflkghlsakndgpiuahdsbnvaiuksdhgvioubaijdscvh