spring:
  application:
    name: ThoughtStream

  cache:
    type: redis

  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: redis
      port: 6379
      ssl:
        enabled: false

  mongodb:
    uri: mongodb://mongodb:27017/thoughtstreamdb


# CUSTOM ENVIRONMENT VARIABLES

jwt:
  secretKey: djklfhaiudhfliuahsjknsjfdngjksdflkghlsakndgpiuahdsbnvaiuksdhgvioubaijdscvh

pagination:
  pageSize: 10